apiVersion: v1
kind: Service

metadata:
  name: hotel-backend-service
  namespace: hotel-app

spec:
  selector:
    app: hotel-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

