apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-backend-config
  namespace: hotel-app
data:
  FLASK_ENV: development
  DATABASE_URL: sqlite:///hotel_reservation.db
  CORS_ORIGINS: http://localhost:5173
  OPENAI_MODEL: "gpt-4.1-mini"
