apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hotel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: hotel-frontend
        image: shoukat999/hotel-ai-reservation-frontend:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
          value: ".amazonaws.com"