apiVersion: v1
kind: Secret
metadata:
  name: hotel-backend-secret
  namespace: hotel-app
type: Opaque
data:
  SECRET_KEY: Y2hhbmdlbWU=
  JWT_SECRET_KEY: Y2hhbmdlLW1lLXRvbw==
  OPENAI_API_KEY: YXBpX2tleQ==